### ISSUE TITLE
Add tests for maybe_fail_import()

### ISSUE THREAD

**Issue by plamut** [googleapis/python-test-utils#44] opened 2021-07-09 09:56 UTC
Context: https://github.com/googleapis/google-cloud-python/pull/8840#issuecomment-876524337

Refactoring the utility required a bit more work than it ideally should, thus we should cover it with tests.

**Comment by parthea** [comment] 2022-02-26 18:16
I'm going to close this as a duplicate of #83

**Closed by parthea** 2022-02-26 18:16 UTC
Labels: type: process
